export { Home } from "../partial/Home" 
export { Header } from "../partial/Header" 
export { Footer } from "../partial/Footer" 
export { Contactus } from "../partial/Contactus"
export { About } from "../partial/About"
export { Pagenotfound } from "../partial/Pagenotfound"